name: CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "dev", "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/jahakaha/halal-bet/ci:latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Linter
        run: golangci-lint run

      - name: Run Tests
        run: go test -v ./...